# Generated by Django 3.0 on 2019-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_image/default.jpg', upload_to='book_image'),
        ),
    ]
