# Generated by Django 3.0 on 2019-12-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.CharField(max_length=210),
        ),
    ]
