# Generated by Django 3.0 on 2019-12-19 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_userprofile_name'),
        ('Book', '0003_auto_20191216_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(default=datetime.date(2019, 12, 26))),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.UserProfile')),
            ],
        ),
    ]
