# Generated by Django 3.0 on 2019-12-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userprofile_name'),
        ('Borrow', '0004_auto_20191219_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserProfile'),
        ),
    ]
